- type: replace
  path: /instance_groups/name=nginx/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        deployment: cf
        from: nats
    properties:
      route_registrar:
        routes:
          - name: locust
            port: 8080
            registration_interval: 20s
            uris:
              - locust.((domain))
        routing_api:
          skip_ssl_validation: true

- type: replace
  path: /releases/name=routing?
  value:
    name: routing
    version: "((routing.version))"
    sha1: ((routing.sha1))
    url: ((repository_base))/routing/routing-((routing.version))-((version-stemcell.os))-((version-stemcell.major)).tgz
    stemcell:
      os: ((version-stemcell.os))
      version: "((version-stemcell.major)).((version-stemcell.minor))"