{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(locust_state, instance)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values(locust_requests_num_requests{instance=~\"$instance\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Locust Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "locust_state{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Connected slaves",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "locust_slave_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Swarmed users",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "locust_user_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current number of users",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "locust_user_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current RPS",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(locust_requests_current_rps{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Fail ratio",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "locust_fail_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(locust_requests_max_response_time{instance=\"$instance\", host=~\"$host\"}) by (host)",
     "legendFormat": "AVG MAX {{host}}"
    },
    {
     "expr": "avg(locust_requests_min_response_time{instance=\"$instance\", host=~\"$host\"}) by (host)",
     "legendFormat": "AVG MIN {{host}}"
    },
    {
     "expr": "avg(locust_requests_avg_response_time{instance=\"$instance\", host=~\"$host\"}) by (host)",
     "legendFormat": "AVG AVG {{host}}"
    },
    {
     "expr": "avg(locust_requests_median_response_time{instance=\"$instance\", host=~\"$host\"}) by (host)",
     "legendFormat": "AVG MEDIAN {{host}}"
    }
   ]
  },
  {
   "title": "Requests per endpoint / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(locust_requests_num_requests{instance=\"$instance\", host=~\"$host\"}[2m])",
     "legendFormat": "{{ method}} {{host}}{{path}}"
    },
    {
     "expr": "rate(locust_requests_num_failures{instance=\"$instance\", host=~\"$host\"}[2m])",
     "legendFormat": "Failed {{ method}} {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Number of users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_user_count{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}